variables:
    # Configure mysql service (https://hub.docker.com/_/mysql/)
    MYSQL_DATABASE: wordpress_tests
    MYSQL_ROOT_PASSWORD: mysql

stages:
    - verify
    - test
    - deploy

PHPCS:PHP7.2:MySQL:
    stage: verify
    image: gagan0123/php:7.2
    script:
        - phpcs
    allow_failure: true

PHPunit:PHP7.3:MySQL:
    stage: test
    image: gagan0123/php:7.3
    services:
        - mysql:5.6
    script:
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql latest true
        - phpunit --configuration phpunit.xml.dist

Deploy:
    stage: deploy
    environment: 
        name: deployment
    image: gagan0123/svn:latest
    when: manual
    script:
        - bash bin/gitlab-deploy.sh